path: "/home/paula/Documentos/PAULA/NOVENO SEMESTRE/ANALISIS/proyecto_frailejones/datasets/19_dic_2024_bajito_mask_test/dataset"
train: images/train
val: images/test
test: images/test
nc: 1
names: [frailejon]
