# -*- coding: utf-8 -*-
"""Estudio del Dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tf5RDTGdcj-VcZLKzN4YK7w2fZLf65x_

# ***ESTUDIO DEL DATASET***
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

ruta_csv = "/content/drive/MyDrive/19_dic_1cm_pedazo_all.csv"
df = pd.read_csv(ruta_csv)
df.head()

"""# **Sobre el dataset:**

Cada fila corresponde a una predicción del modelo de detección de Frailejones en una de las teselas de los ortomosaicos.
"""

print("Número total de detecciones:", len(df))
print("\nResumen estadístico:")
df.describe()

"""## ***Descripción de columnas***
- **id:**	Identificador del frame o imagen donde se detectaron objetos (en este caso, todos son 1.0, parece un solo frame).

- **xmin:** Longitud mínima del bounding box (esquina inferior izquierda).

- **ymin:**	Latitud mínima del bounding box.

- **xmax:**	Longitud máxima del bounding box (esquina superior derecha).

- **ymax:** Latitud máxima del bounding box.

- **confidence:**	Confianza del modelo de detección.

"""

df['width'] = df['xmax'] - df['xmin']
df['height'] = df['ymax'] - df['ymin']
df['area'] = df['width'] * df['height']

df[['width', 'height', 'area']].describe()

fig, axs = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(df['width'], bins=30, ax=axs[0], color='skyblue')
axs[0].set_title('Distribución del ancho (width)')

sns.histplot(df['height'], bins=30, ax=axs[1], color='salmon')
axs[1].set_title('Distribución del alto (height)')

sns.histplot(df['area'], bins=30, ax=axs[2], color='lightgreen')
axs[2].set_title('Distribución del área de las cajas')

plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='xmin', y='ymin', data=df, alpha=0.4, edgecolor=None)
plt.title("Distribución espacial de detecciones (xmin vs ymin)")
plt.xlabel("xmin")
plt.ylabel("ymin")
plt.gca().invert_yaxis()
plt.show()

"""Cada punto azul representa una detección de un Frailejón, esta distribución no es uniforme, lo que es esperable ya que refleja la concentración natural de Frailejones en ciertas zonas del ecosistema."""

import folium
from shapely.geometry import box
from folium import Map, features

m = folium.Map(location=[df["cy"].mean(), df["cx"].mean()], zoom_start=17)

for _, row in df.iterrows():
    bounds = [[row["ymin"], row["xmin"]], [row["ymax"], row["xmax"]]]
    folium.Rectangle(bounds=bounds, color="blue", fill=True, fill_opacity=0.2).add_to(m)
m

"""Aquí es posible observar la distribución espacial de las detecciones realizadas por el modelo de detección de Frailejones. Cada punto azul indica la posición de una caja predictiva y se puede observar lo siguiente:

- Una alta concentración de detecciones en ciertas zonas lo que puede reflejar una mayor densidad de Frailejones en el terreno o una tendencia del modelo a sobredetectar en áreas vegetativamente complejas.

- Zonas más vacías o con menos detecciones, que podrían corresponder a sectores con menos presencia de frailejones o errores de segmentación.

Este tipo de visualización permite apreciar la cobertura espacial del modelo y además, identificar regiones que podrían beneficiarse de un refinamiento del modelo, ajustes en el umbral de confianza, o incluso una revisión manual para identificar falsos positivos o falsos negativos; por ejemplo, aquellas donde los bounding boxes tienden a tomar más de un frailejon como uno y no permite un conteo adecuado de la cantidad de frailejones en una zona.
"""

